name: BlockTrack
main: com.nbpe.blocktrack.BlockTrack
author: nbpe
version: 1.0.2
api: ["1.0.0"]
depend: [DbLib]
description: BlockTrack for NukkitX
commands:
   blocktrack:
      description: Check the number of blocks placed and broken by a player.
      usage: "/blockTrack <player> [total broken/placed]/[blockName]"
      permission: block.track
      permission-message: You don't have <permission>

permissions:
  blocktrack.history:
    description: "BlockTrack History"
    default: op
  blocktrack.track:
    description: "BlockTrack Track"
    default: op